groups:
  - name: fastapi_alerts
    rules:
      # High Error Rate Alert
      - alert: HighErrorRate
        expr: rate(fastapi_errors_total[5m]) > 0.1
        for: 2m
        labels:
          severity: warning
          service: fastapi
        annotations:
          summary: "High error rate detected"
          description: "Error rate is {{ $value }} errors per second for the last 5 minutes"

      # High Response Time Alert
      - alert: HighResponseTime
        expr: histogram_quantile(0.95, rate(fastapi_request_duration_seconds_bucket[5m])) > 1
        for: 5m
        labels:
          severity: warning
          service: fastapi
        annotations:
          summary: "High response time detected"
          description: "95th percentile response time is {{ $value }}s"

      # Application Down Alert
      - alert: ApplicationDown
        expr: up{job="fastapi-app"} == 0
        for: 1m
        labels:
          severity: critical
          service: fastapi
        annotations:
          summary: "FastAPI application is down"
          description: "FastAPI application has been down for more than 1 minute"

      # High Memory Usage Alert
      - alert: HighMemoryUsage
        expr: system_memory_usage_percent > 80
        for: 5m
        labels:
          severity: warning
          service: system
        annotations:
          summary: "High memory usage detected"
          description: "Memory usage is {{ $value }}%"

      # High CPU Usage Alert
      - alert: HighCPUUsage
        expr: system_cpu_usage_percent > 80
        for: 5m
        labels:
          severity: warning
          service: system
        annotations:
          summary: "High CPU usage detected"
          description: "CPU usage is {{ $value }}%"

      # Database Connection Issues
      - alert: DatabaseConnectionIssues
        expr: database_connections_active < 5
        for: 2m
        labels:
          severity: warning
          service: database
        annotations:
          summary: "Low database connections"
          description: "Only {{ $value }} database connections active"

      # Business Metrics - High Order Processing Time
      - alert: HighOrderProcessingTime
        expr: histogram_quantile(0.95, rate(order_processing_duration_seconds_bucket[10m])) > 2
        for: 5m
        labels:
          severity: warning
          service: business
        annotations:
          summary: "High order processing time"
          description: "95th percentile order processing time is {{ $value }}s"

  - name: system_alerts
    rules:
      # Node Exporter Down
      - alert: NodeExporterDown
        expr: up{job="node-exporter"} == 0
        for: 1m
        labels:
          severity: critical
          service: monitoring
        annotations:
          summary: "Node Exporter is down"
          description: "Node Exporter has been down for more than 1 minute"

      # High Disk Usage
      - alert: HighDiskUsage
        expr: system_disk_usage_percent > 85
        for: 5m
        labels:
          severity: critical
          service: system
        annotations:
          summary: "High disk usage detected"
          description: "Disk usage is {{ $value }}%"

      # Container High Memory Usage
      - alert: ContainerHighMemoryUsage
        expr: (container_memory_usage_bytes / container_spec_memory_limit_bytes) * 100 > 80
        for: 5m
        labels:
          severity: warning
          service: containers
        annotations:
          summary: "Container high memory usage"
          description: "Container {{ $labels.name }} memory usage is {{ $value }}%"
